### ISSUE TITLE
[!!!] TOOL_MENU / TO-DO LIST

### ISSUE THREAD

**Issue by till-teb** [till-teb/expenses-management-tool#12]
The superior function `tool_menu` should guide the user through the program and all functions.
The main-tool-menu-function could be structured like this:

**_We can also use our main menu as our to do list._** 
:)

## **main menu /  todo list**:
welcome user , choose option :
### {already coded}:
   - **`input new expense`** (query function)       
   - **`input day_label`** function (0 or 1 for good day/ bad day to label the days) 
  
### {not coded yet}:
   
   - **`statistics function`** 
      - `numeric analyses`
      - `graphical analyses`
      - `clustering analyses` 
   - **`example-data-generator`** function
   - **`predict-future-expenses`** function

**_other open functions that needs to be coded:_**
- **` create Dashboard using streamlit`** function
- **`test functions` and `testing workflows`**

# Next steps:

**Therefore, I suggest everyone picks an area where he's feeling comfortable and like to go more in depth there.
Please comment `name` and `your wish function`**

Please leave feedback 👍

**Comment by adhamarif** [comment]
Hi, I'm interested to do `input day_label`. Then maybe I'll take a look to create Dashboard using streamlit as suggested from Prof. Huber.

`Adham` : `input day_lable`

**Comment by till-teb** [comment]
> `Adham` : ` create Dashboard using streamlit` 

okay great, I m write that down 😇
