### ISSUE TITLE
add basic package structures

### ISSUE THREAD

**Issue by adhamarif** [till-teb/expenses-management-tool#19]
should we add basic package structure (such as .gitignore)?

I saw Prof Huber suggest us to do it with cookiecutter, link here https://github.com/florian-huber/python-template .

My concern is that, the software template from cookiecutter need to be done before a repository is created. I dont know if there is another way to add the template after the repository is created.

If not, maybe we could add the file manually. Maybe we could ask Prof Huber for consultation

Attention project manager @till-teb

**Comment by till-teb** [comment]
yeah, really good mentioned. I thought about the structure too. I did t knew how to build that structure. I think its a good was when we ask our Professor on the next lecture right @adhamarif
