### ISSUE TITLE
statistics function

### ISSUE THREAD

**Issue by till-teb** [till-teb/expenses-management-tool#2]
The data structure behind the expenses-management-tool is a huge DataFrame. It contains the following columns:

- expense
- amount
- importance
- category
- date
- label for good day or bad day

________________________________________________
**for the `statistics function`:**
A large menu of analyses should appear when opening the `statistics function`. A subdivision into graphical plots and the key facts could be a good subdivision.

`previous analyses:` 

-  
-  
-  
- 
 - _please always add new analyses to the list_

**Comment by adhamarif** [comment]
**Donut chart** could be interesting if we would like to compare percentage of our monthly expenses by _categories_ or _importance_.

Example of donut chart:
![image](https://user-images.githubusercontent.com/92054450/203870747-6794178f-6697-49ca-8e15-0c2043714626.png)

At the centre of the donut, we could write total monthly expenses.

**Comment by till-teb** [comment]
I really like donuts and donuts charts. 😂

great idea Adham
