### ISSUE TITLE
git still track pycache file

### ISSUE THREAD

**Issue by adhamarif** [till-teb/expenses-management-tool#34]
I had a merge conflict before and it's just because of `pycache` files. I wonder why it still tracked `pycache `eventhough it's belong to `.gitignore`

Maybe we need to delete pycache files in main so that it stops tracking change.

Pull request has been made in #32 #33

**Comment by l4nz8** [comment]
Is the error still up to date or has the problem already been fixed?

**Comment by adhamarif** [comment]
the pycache is not there but another issue is git tracking our csv file. is it okay if we remove that too?

**Comment by l4nz8** [comment]
I would say that we can remove the files and should put them in git ignore

**Comment by l4nz8** [comment]
ok i have updated our .ignore and removed all .csv files from our project
