### ISSUE TITLE
Decide expense categories

### ISSUE THREAD

**Issue by adhamarif** [till-teb/expenses-management-tool#4]
Category is one of the important component in this project. @till-teb also mentioned this in #1

Now we need to decide how many categories should we have in this project. I think it would be better if we have a few of general categories and its sub-category.

Example:

- Food & Beverages
  - Bakery
  - Grocery
  - Restaurant

- Shopping
  - Online shopping
  - Department stores

- Lifestyle
  - Cigarette
  - Online subscription
  - Alcohol

My suggestion is that we have around 5-7 simplified category, with each have maximum 3-4 subcategory.

**Comment by adhamarif** [comment]
We should start to discuss the main category first, I have a few to suggest.

- Food & Beverages
- Shopping
- Lifestyle / Entertainment
- Household & Utilities
- Transportation

If you guys have something to add or remove, please don't hesitate to share me your idea!

**Comment by till-teb** [comment]
I'm so glad you've already thought about possible categories. I find your ideas very valuable. I have thought about the following logical categories by opening my online banking and trying to categorize all the expenses I have. My result are the following columns: 

(1) `Food`                        example: Rewe, Aldi, Bäckerei.....
(2) `consumer goods`                             example: DM oder so Sachen, die man braucht um zu leben.....
(3) `transportation`                              example: Kosten für Bahn oder Auto Transporte .....
(4) `housing`                                example: Strom, Wlan......
(5) `free time expenses`                         example: Restaurants, Ausflüge, Freizeitausgaben.....
(6) `insurance + taxes`                              example: Hausrat, Auto Versicherung, Steuern, Rundfunkgebühren.....
(7) `bank + savings investments`                     example: Kontoführungsgebühren, Investments, Sparpläne.....
(8) `other + extraordinary expenses`                      example: Urlaub, Außergewöhnliche Ausgaben.....

What do you think about these suggestions?

Please add your ideas 🤓

**Comment by till-teb** [comment]
!!! So it would be cool if we all can agree on some ` logical categories `there. So that everyone can express his opinion, I ask you all for the favor:

**Please think about meaningful divisions for the categories and write your ideas in the comments :) !!!**

**Comment by adhamarif** [comment]
Hi, I find (7) `bank + savings investments` will be useful because later we can integrate it with the `savings tracker` function.

Overall I find you ideas are good!

**Comment by till-teb** [comment]
> okay great, but can you tell me more about your subcategories in mind?  @velixko
